#!/bin/bash

# This script will trigger a new Sonarr backup, grab a list of all available
# Sonarr backups, download the most recent one (should be the one that was just
# started), then excrypt it and upload it to google drive.
#
# To run, this script requires a few environment variables be passed in to it.
# The variables required are:
#
# SONARR_API_KEY: The auth token for Sonarr's API.
# SONARR_URL: The base URL for Sonarr.
# SONARR_BACKUP_PASSWORD: The password to encrypt the backup with.
#
# This script requires the commands jq, rclone, wget, curl, and openssl.

curl -v --header "X-Api-Key: $SONARR_API_KEY" -d '{"name": "backup"}' $SONARR_URL/api/command

sleep 10

SONARR_LAST_BACKUP=`curl -v --header "X-Api-Key: $SONARR_API_KEY" "$SONARR_URL/api/system/backup" | /usr/local/bin/jq --raw-output 'sort_by(.time) | .[-1]'`

SONARR_LAST_BACKUP_LOCATION=`echo $SONARR_LAST_BACKUP | /usr/local/bin/jq --raw-output '.path'`
SONARR_LAST_BACKUP_TIME=`echo $SONARR_LAST_BACKUP | /usr/local/bin/jq --raw-output '.time'`
FORMATTED_TIME=`date -j -f "%Y-%m-%dT%H:%M:%SZ" $SONARR_LAST_BACKUP_TIME +%Y.%m.%d_%H.%M`
LOCAL_BACKUP_DESTINATION="/Users/gabe/Downloads"
BACKUP_DESTINATION_FILE=$LOCAL_BACKUP_DESTINATION/Sonarr_backup_$FORMATTED_TIME.zip

/usr/local/bin/wget "--header=X-Api-Key: $SONARR_API_KEY" -O "$BACKUP_DESTINATION_FILE" "$SONARR_URL$SONARR_LAST_BACKUP_LOCATION"

openssl aes-256-cbc -a -salt -pass "pass:$SONARR_BACKUP_PASSWORD" -in "$BACKUP_DESTINATION_FILE" -out "$BACKUP_DESTINATION_FILE.bin"

rm $BACKUP_DESTINATION_FILE

/usr/local/bin/rclone --config /Users/gabe/.config/rclone/rclone.conf -v move "$BACKUP_DESTINATION_FILE.bin" GDrive:Backups/Sonarr\ DB
