#!/bin/bash

# This backup program will use hash backup to backup the entire
# contents of my Plex videos directory to Google drive.
# It will send a notification that the backup is starting
# before it is run. The hb command will output the log
# into a file. hb will only upload files that have
# changed. Any files that would be deleted or overwritten
# will be versioned by hash backup. When finished, this
# will send a push notificaiton using pushover.com.

# Create constants
PUSH_NOTIFICATION_DIRECTORY="/share/Web/bin/push_notifications/backups"
# The hash backup executable
hb="/share/Web/bin/hb"

# Send a starting notification
$PUSH_NOTIFICATION_DIRECTORY/push \
"Backup started" \
"Started backing up the Plex Videos directory.";

# Run hash backup
$hb \
	log \
	backup \
	-c /share/Backups/plex/media \
	/share/Media/Videos

# Send a notification the backup finished, and include
# a link to view the log on the web
$PUSH_NOTIFICATION_DIRECTORY/push \
	"Backup finished" \
	"Finished backing up the Plex Videos directory.";
