#!/bin/bash

# This backup program will use rclone to upload the entire
# contents of my Plex directory to my encrypted remote.
# It will send a notification that the backup is starting
# before it is run. The rclone command will output the log
# into a file. rclone will only upload files that have
# changed. Any files that would be deleted or overwritten
# will be moved into a backup directory on the remote,
# allowing for versioning of the files. When finished, this
# will send a push notificaiton using pushover.com that will
# include a link to view the log file on the web.

# Create constants
PUSH_NOTIFICATION_DIRECTORY=/share/Web/push_notifications/backups
# Create a string like `2018-02-19_14:16:51`
datename="$(date '+%Y-%m-%d_%H:%M:%S')"
logfile="$datename.log"
# The rclone executable
$rclone=/share/Web/rclone/rclone

# Send a starting notification
$PUSH_NOTIFICATION_DIRECTORY/push \
"Backup started" \
"Started backing up the Plex root directory.";

# Run rclone. This will run the rclone executable in
# `/share/Web`. It will use the the rclone config file.
# It will log info stats into the specified log file. All
# files that would be deleted or overwritten will be moved
# into a backup folder to keep versioned backups. It will
# ignore QNAP folders `Recycle` and `Recently-Snapchot`,
# and all hidden files and folders. It will also ignore
# Photos, as that has its own backup location. It will use
# 128 checkers, checking only with the file's md5sum.
$rclone \
	--config /share/Web/rclone/rclone.conf \
	--log-file "/share/Web/rclone/logs/$logfile" \
	--log-level INFO \
	--backup-dir "GDriveVideosBackup:Previous/$datename" \
	--exclude '@Recently-Snapshot/**' \
	--exclude '@Recycle/**' \
	--exclude 'Photos/**' \
	--exclude '.*{/**,}' \
	--checkers 128 \
	--checksum \
	--ignore-size \
	--track-renames \
	sync \
	/share/Plex/ \
	GDriveVideosBackup:Current/

# Send a notification the backup finished, and include
# a link to view the log on the web
$PUSH_NOTIFICATION_DIRECTORY/push-url \
	"Backup finished" \
	"Finished backing up the Plex root directory." \
	"rclone-logs.grevells.duckdns.org/$logfile" \
	"View log"
