#!/bin/bash

# This backup program will use rclone to upload the entire
# contents of my Plex directory to my encrypted remote.
# It will send a notification that the backup is starting
# before it is run. The rclone command will output the log
# into a file. rclone will only upload files that have
# changed. Any files that would be deleted or overwritten
# will be moved into a backup directory on the remote,
# allowing for versioning of the files. When finished, this
# will send a push notificaiton using pushover.com that will
# include a link to view the log file on the web.

# Create constants
PUSH_NOTIFICATION_DIRECTORY="/share/Web/bin/push_notifications/backups"
# Create a string like `2018-02-19_14:16:51`
datename="$(date '+%Y-%m-%d_%H:%M:%S')"
logfile="$datename.log"
# The hash backup executable
hb="/share/Web/bin/hb"

# Send a starting notification
$PUSH_NOTIFICATION_DIRECTORY/push \
"Backup started" \
"Started backing up the Plex Videos directory.";

# Run hash backup
$hb \
	log \
	backup \
	-c /share/Backups/plex/media \
	/share/Media/Videos

# Send a notification the backup finished, and include
# a link to view the log on the web
$PUSH_NOTIFICATION_DIRECTORY/push-url \
	"Backup finished" \
	"Finished backing up the Plex Videos directory." \
	"http://rclone-logs.grevells.duckdns.org/$logfile" \
	"View log"
